#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

    if ps -o args= $PPID | grep -E -q ' --no-verify| -n | -n$' ; then
        echo "Skipping prepare-commit-msg\n"
    else
        exec < /dev/tty && node_modules/.bin/cz --hook || true
    fi

